apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Externer Port (LoadBalancer)
      targetPort: 80 # Interner Port (Pod)
